#!/bin/sh
if [ $# -lt 1 ]; then
	echo "Usage: ./install <directory>"
	exit
fi

echo "import setuptools" > setup.py
name='tarloader'
echo "setuptools.setup(name='${name}')" >> setup.py
python3 setup.py develop --install-dir $@
rm -f setup.py

